### ISSUE TITLE
Erratic Rotary Encoder

### ISSUE THREAD

**Issue by ModchipMan** [DeeEmm/DIY-Flow-Bench#24] opened 2019-12-24 10:44 UTC
This could be my wiring issue.
I have the 2 x Caps 150n attached
fly lead length is about 2ft long from encoder to arduino.
Pin A = D2
Pin B = D3
Pin C= GND
switchP1 = GND
switchP2 = D5
 
Issue is it will only go in a down direction with counter clockwise rotation or clockwise rotation, The push button for OK is very hit and miss to function.

**Comment by DeeEmm** [comment] 2019-12-26 04:33
Do you get the same results if the caps are removed?

**Comment by ModchipMan** [comment] 2019-12-26 06:21
Its the same with or with out caps..

**Comment by ModchipMan** [comment] 2019-12-29 23:50
I have found out what is causing this, 
its the the delays in program
I created a simple menu with tcMenu and it worked a treat, as soon as i added delay(1000); in to program, the encoder become very hit and miss..

**Comment by ModchipMan** [comment] 2019-12-29 23:50
Also, the encoder needs the 150n caps, or it also becomes erratic.

**Comment by DeeEmm** [comment] 2019-12-30 01:31
Cool. Good catch. I will remove the delay from the next update. Just set it to zero for the time being.

The delay was only there to give us an easy way to stabilise the display readout. We can also achieve that by other methods. (eg sample average).

**Comment by DeeEmm** [comment] 2019-12-30 01:34
What build are you using?

The delay has already been removed in the latest version

**Comment by DeeEmm** [comment] 2020-08-03 12:01
Any update on this?

**Comment by DeeEmm** [comment] 2020-08-06 14:42
I'm going to close this one out. I cannot reproduce it.

**Closed by DeeEmm** 2020-08-06 14:42 UTC
Labels: invalid
